name: Angular UI deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Docker build tag
        id: set-tag
        run: echo "DOCKER_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Clean docker system
        run: |
          sudo docker system prune -af

      - name: build docker image
        run: |
          sudo docker build -t angular-ui:$DOCKER_TAG .

      # - name: Print Docker Username
      #   run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"

      # - name: Print Docker Password (partial)
      #   run: echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD:0:4 }}*

      - name: Login to Docker Registry
        run: |
          sudo docker login -u ${{ secrets.DOCKERHUB_UNAME }} --password ${{ secrets.DOCKERHUB_PASSWD }}

      # - name: Log in to Docker Hub
      #   run: |
      #     echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker tag
        run: |
          sudo docker tag angular-ui:$DOCKER_TAG ramupunuru/angular-ui:$DOCKER_TAG

      - name: Push Docker Image
        run: sudo docker push ramupunuru/angular-ui:$DOCKER_TAG

      - name: Checkout code k8s-manifest repo
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v3
        with:
          repository: ramupunuruorg/k8s-manifests
          github-server-url: https://github.com/
          ref: "main"
          sparse-checkout: |
            apps/angular_pod.yml
          sparse-checkout-cone-mode: false
          token: ${{ secrets.GIT_PA_TOKEN }}

      - name: Update Image Tag in Kubernetes Manifest
        run: |
          sudo sed -i 's;ramupunuru/angular-ui:.*;ramupunuru/angular-ui:'"$DOCKER_TAG"';g' ./apps/angular_pod.yml
          cat ./apps/angular_pod.yml
      - name: commit and push changes
        # if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
        run: |
          git config --global user.email "ramupunuru@gmail.com"
          git config --global user.name "krish"
          git add . && git commit -m "change image tag for angular-ui service $DOCKER_TAG"
          git push origin main
