name: Angular UI deployments
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Docker build tag
        id: set-tag
        run: echo "DOCKER_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Clean docker system
        run: |
          sudo docker system prune -af

      - name: build docker image
        run: |
          sudo docker build -t idp-ui:$DOCKER_TAG .

      - name: Login to Docker Registry
        run: | 
          sudo docker login -u ${{ secrets.DOCKERHUB_UNAME }} --password ${{ secrets.DOCKERHUB_PASSWD }}  

      - name: docker tag
        run: |
          sudo docker tag idp-ui:$DOCKER_TAG krishnamaram2/idp-ui:$DOCKER_TAG
    
      - name: Push Docker Image
        run: sudo docker push krishnamaram2/idp-ui:$DOCKER_TAG

      - name: Checkout code idp-deployments repo
        if: github.ref == 'refs/heads/main' 
        uses: actions/checkout@v3
        with:
          repository: cloudstonesorg/idp-deployments
          github-server-url: https://github.com/
          ref: 'main'
          sparse-checkout: |
            apps/idp/idp_ui.yml
          sparse-checkout-cone-mode: false
          token: ${{ secrets.GIT_PA_TOKEN }}

      - name: Update Image Tag in Kubernetes Manifest
        run: |
          sudo sed -i 's;krishnamaram2/idp-ui:.*;krishnamaram2/idp-ui:'"$DOCKER_TAG"';g' ./apps/idp/idp_ui.yml
          cat ./apps/idp/idp_ui.yml
      - name: commit and push changes
        # if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
        run: |
          git config --global user.email "krishnamaram2@gmail.com"
          git config --global user.name "krish"
          git add . && git commit -m "change image tag for idp-ui service $DOCKER_TAG"
          git push origin main